@startuml "Enfer"

left to right direction

class Matchesimple{

}
class Matchdouble{

}

class Arbitre{
    attribut : name
}

class Joueurs{
    attribut : name
    attribut : capitaine flag
    attribut : classement
}

class Set{
    methode : service()
}

class Score{

}

class Rencontre{

}
class Historique{

}


@enduml