@startuml "Enfer"

left to right direction

class Matchesimple{

}
class Matchedouble{

}


class Arbitre{
    attribut : name
}

class Joueurs{
    attribut : name
    attribut : capitaine
    attribut : classement
}

class Set{
}

class Score{

}

class Rencontre{

}
class Historique{

}

Joueurs <--o Rencontre : aggrégation
Matchesimple *-->Rencontre : composition
Matchedouble *-->Rencontre : composition

Historique*-->Score : composition

Arbitre *--> Matchesimple
Arbitre *--> Matchedouble






@enduml