@startuml "Enfer"

left to right direction
skinparam Linetype polyline
skinparam linetype ortho


class Matchesimple{

}
class Matchedouble{

}


class Arbitre{
    attribut : name
}

class Joueurs{
    attribut : name
    attribut : capitaine
    attribut : classement
}

class Set{
}

class Score{

}

class Rencontre{

}
class Historique{

}

Joueurs <--o Rencontre
Matchesimple <--o Rencontre
Matchedouble <--o Rencontre

Historique*-->Score

Arbitre *--> Matchesimple
Arbitre *--> Matchedouble

Set *--> Score
Matchesimple *-->Set
Matchedouble *-->Set






@enduml